# PLAY 2: Update Inventory on the Ansible Server
- name: Remove existing entry for the VM if it exists
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/../inventory"
    regexp: "^{{ hostvars['kvm_host']['vm_name'] }}\\b"
    state: absent
  delegate_to: localhost
  when: new_vm_ip is defined

- name: Add new VM to inventory file
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}/../inventory"
    insertafter: '^\[newly_provisioned_vms\]'
    line: "{{ hostvars['kvm_host']['vm_name'] }} ansible_ssh_host={{ new_vm_ip }}"
    state: present
  delegate_to: localhost
  when: new_vm_ip is defined

- name: Commit and push to GitHub (Stateless Mode)
  ansible.builtin.shell: |
    git config --global user.email "kersmaka@gmail.com"
    git config --global user.name "AAP Runner"
    git config --global --add safe.directory /runner/project
    cd /runner/project
    rm -rf .git
    git init -b main
    git remote add origin https://{{ github_token }}@github.com/kersmaka/ansible.git
    git fetch origin main
    git reset origin/main
    git add inventory
    git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update {{ hostvars['kvm_host']['vm_name'] }} in inventory" && git push origin main)
  delegate_to: localhost
  when: new_vm_ip is defined