
- name: Generate AAP Backup on Source
  when: "'source' in group_names"
  block:
    - name: Run AAP Backup Playbook
      ansible.builtin.command:
        cmd: ansible-playbook -i inventory ansible.containerized_installer.backup
        chdir: "{{ installer_path }}"
      register: backup_run
      ignore_errors: yes  # Allows us to see the output even on failure

    - name: Debug backup failure
      ansible.builtin.debug:
        msg: "{{ backup_run.stdout_lines }}"
      when: backup_run.rc != 0
      
    - name: Compress backup directory
      ansible.builtin.shell:
        cmd: "tar -cvzf {{ backup_archive }} backups/"
        chdir: "{{ installer_path }}"
    - name: Fetch backup to local controller
      ansible.builtin.fetch:
        src: "{{ installer_path }}/{{ backup_archive }}"
        dest: "{{ local_tmp_path }}/"
        flat: yes
