
- name: Generate AAP Backup on Source
  when: "'source' in group_names"
  block:
    - name: Run AAP Backup Playbook
      ansible.builtin.command:
        cmd: ansible-playbook -i inventory ansible.containerized_installer.backup
        chdir: "{{ installer_path }}"
      # We switch from root to the aap user here
      become: yes
      become_user: aap
      environment:
        HOME: "/home/aap"
      register: backup_run

    - name: Debug backup failure
      ansible.builtin.debug:
        msg: "{{ backup_run.stdout_lines }}"
      when: backup_run.rc != 0

    - name: Compress backup directory
      ansible.builtin.shell:
        cmd: "tar -cvzf {{ backup_archive }} backups/"
        chdir: "{{ installer_path }}"
