---
    - name: Clean all DNF cache
      ansible.builtin.command:
        cmd: dnf clean all
      changed_when: true

    - name: Install Foreman release RPM
      ansible.builtin.dnf:
        name: https://yum.theforeman.org/releases/3.17/el9/x86_64/foreman-release.rpm
        state: present
        disable_gpg_check: true

    - name: Install Katello repos RPM
      ansible.builtin.dnf:
        name: https://yum.theforeman.org/katello/4.19/katello/el9/x86_64/katello-repos-latest.rpm
        state: present
        disable_gpg_check: true

    - name: Install Puppet 8 release RPM
      ansible.builtin.dnf:
        name: https://yum.puppet.com/puppet8-release-el-9.noarch.rpm
        state: present
        disable_gpg_check: true

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true
      register: dnf_upgrade

    - name: Add host entry to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
        regexp: "^{{ ansible_default_ipv4.address }}"
        state: present  

    - name: Reboot if kernel was updated
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: dnf_upgrade.changed and "'kernel' in dnf_upgrade.results | join(' ')"

    - name: Install foreman-installer-katello
      ansible.builtin.dnf:
        name: foreman-installer-katello
        state: present