- name: Initialize continue_prompt
  set_fact:
    continue_prompt: ''

- name: Prompt user for input and confirmation (looping)
  block:
    - name: Include prompt tasks and potentially loop the entire prompt process
      include_tasks: prompt.yml
      loop: [ {} ] # Execute the prompt tasks at least once (optional)
  # You likely don't need a loop here on the block itself

- name: Final output
  debug:
    msg: |
      Continue Prompt: "{{ continue_prompt }}"
      User Input: "{{ user_input_variable.user_input | default('No input provided') }}"