- name: Prompt for user input
  prompt:
    name: user_input
    prompt: "Please enter some text:"
    private: no
  register: user_response

- name: Set user_input_variable fact
  set_fact:
    user_input_variable: "{{ user_response }}"

- name: Prompt for confirmation (retry until 'y')
  prompt:
    name: continue_prompt_input
    prompt: "Do you want to continue? (y/n)"
    private: no
  register: continue_response
  until: continue_response.user_input == 'y'
  retries: 3 # Optional: Limit the number of retries
  delay: 2 # Optional: Wait time between retries

- name: Set continue_prompt fact
  set_fact:
    continue_prompt: "{{ continue_response.user_input }}"