---
- name: Verify rhel_system_roles collection in Execution Environment
  hosts: "{{ target }}"
  gather_facts: false # Not strictly necessary for this demo, but often good practice for specific role usage

  tasks:
    - name: Ensure rhel_system_roles.timesync role is available and used
      # Use the fully qualified collection name (FQCN)
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.timesync
      vars:
        timesync_ntp_servers:
          - hostname: 0.rhel.pool.ntp.org
            iburst: yes
          - hostname: 1.rhel.pool.ntp.org
            iburst: yes
          - hostname: 2.rhel.pool.ntp.org
            iburst: yes
        timesync_ntp_enable: true
        timesync_verify_ntp_on_finish: true # This will check NTP status
