---
- name: Test Encrypted Password
  hosts: testing
  vars_files:
    - /home/admin/github/ansible/playbooks/vault_password.yml
  tasks:
    - name: Print the decrypted password
      debug:
        msg: "The decrypted password is {{ my_password }}"

