- hosts: "{{ target }}"
  become: true
  gather_facts: false
  tasks:

  - name: Wait for ready hosts
    ansible.builtin.wait_for_connection:
      timeout: 300
  
- hosts: "{{ target }}"
  become: true
  gather_facts: true
  roles:
    - role: vault_authentication
    - role: vault_variable_loop
    #- role: vault_ssh_keys
    #- role: vault_variable_test
