# 1. pip install hvac
# 2. ansible-galxy collection install community.hashi\_vault

- name : Get the Krabby Patty Secret Formula From Hasicorp Vault
  hosts: 127.0.0.1
  tasks:

  - name: Read the latest version of a kv2 secret from Vault via the remote host with userpass auth
    community.hasi_vault.vault_kv2_get:
      url: https://192.168.0.225:8200/v1/secret-recipes/data/krabby-patty
      engine_mount_point: secret-recipes
      path: krabby-patty # equivalent APIT path is secret-recipes/data/krabby-patty
      namespace: admin/ansible
      auth_method: userpass
      username: crabs
      password: password
    register: response

  - name: Display the results
    ansible.builtin.debug:
    msg:
      - "Secret: {{ response.secret }}"