---
- name: Test
  hosts: localhost
  vars:
    vault_secrets_list:
      - "secret-recipes/data/krabby-patty"
      # Add more secret paths here if needed
  tasks:
    - name: test
      community.hashi_vault.vault_read:
        url: https://192.168.0.225:8200
        token: hvs.4icVDQC4UHjq3iTE0A8d52kO
        path: "{{ item }}"
        validate_certs: false
      loop: "{{ vault_secrets_list }}"
      register: vault_data

    - name: Set namespaced Facts
      set_fact:
        ford_vault: "{{ ford_vault | default({})} | combine ({ item.item: item.data.data }) }}"
      loop: "{{ vault_data.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Display the secret
      ansible.builtin.debug:
        var: vault_data.results
